### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by d4x1** [DjDeveloperr/WatchfaceEditor#1]

**Comment by DjDeveloperr** [comment]
It is not complete yet. Didn't get time to complete it as I had got busy with other main projects.

**Comment by d4x1** [comment]
> It is not complete yet. Didn't get time to complete it as I had got busy with other main projects.

Is there any design doc ? I'm learning React recently. maybe I can contribute some codes.  :)

**Comment by DjDeveloperr** [comment]
> Is there any design doc ?

Not currently. But contributions are welcome!
